before_script:
  - uname -a
  - cat /etc/issue
  - apt-get update
  - apt-get install -y -qq lib32ncurses5 lib32z1 > /dev/null
  - apt-get install -y pandoc
  - apt-get install -y make  
  - apt-get install -y texlive-xetex -y
  - apt-get install -y texlive-latex-recommended # main packages
  - apt-get install -y texlive-latex-extra # package titlesec
  - apt-get install -y fonts-arphic-gbsn00lp fonts-arphic-ukai # from arphic
  - apt-get install -y ttf-wqy-microhei ttf-wqy-zenhei
  - echo machine git.rt-thread.com login $CI_REGISTRY_USER password $CI_REGISTRY_PASSWORD >> ~/.netrc
  - echo machine github.com login $CI_REGISTRY_USER password $CI_REGISTRY_PASSWORD >> ~/.netrc
  - git config --global http.sslVerify false

build_docs:
  script:
    - git clone https://git.rt-thread.com/document/samples.git ./document/samples
    - cd ./document/samples/docs
    - make